import "@radix-ui/themes/styles.css";
import "./theme-config.css";
import "./globals.css";
export const runtime = "edge";
import { Inter, Noto_Sans_Arabic } from "next/font/google";
import Navbar from "./Navbar";
import { Theme, ThemePanel } from "@radix-ui/themes";
import AuthProvider from "@/app/AuthProvider";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });
const notoSansArabic = Noto_Sans_Arabic({
  subsets: ["arabic"],
  display: "swap",
  // adjustFontFallback: false, // 👈
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  // console.log("Where am I?");
  // const { data: session, status } = useSession();
  // console.log(session, status);

  // if (status === "authenticated") {
  //   console.log("Where am I again a little?");

  // return <p>Signed in as {session.user?.email}</p>;
  // }
  // const serverSession = await auth();
  // console.log("serverSession", serverSession);
  return (
    <html lang="en">
      <body className={inter.variable}>
        <AuthProvider>
          <Theme accentColor="plum" grayColor="mauve" radius="large">
            <Navbar />
            <main className="menu-container p-5">{children}</main>
            {/* <ThemePanel/> */}
          </Theme>
        </AuthProvider>
      </body>
    </html>
  );
}
